-- ===============================================================================
-- PROJETO: Pokémon FireRed Version — SQL Server Database Lab
-- ARQUIVO: database/01_create_tables.sql
-- DESCRIÇÃO: Script DDL para criação do Banco de Dados e das 8 Tabelas Relacionais
-- AUTOR: David Bastos
-- ===============================================================================

USE master;
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'PokemonFireRed')
BEGIN
    CREATE DATABASE PokemonFireRed;
END;
GO

USE PokemonFireRed;
GO


CREATE TABLE POKEMON (
     ID_POKEMON INT NOT NULL
    ,NOME VARCHAR(100) NOT NULL
    ,CONSTRAINT PK_POKEMON PRIMARY KEY (ID_POKEMON)
    ,CONSTRAINT UQ_NOME_POKEMON UNIQUE (NOME)
);
GO


CREATE TABLE TIPO (
     ID_TIPO INT NOT NULL
    ,NOME VARCHAR(100) NOT NULL
    ,CONSTRAINT PK_TIPO PRIMARY KEY (ID_TIPO)
    ,CONSTRAINT UQ_NOME_TIPO UNIQUE (NOME)
);
GO


CREATE TABLE LOCAL (
     ID_LOCAL INT NOT NULL
    ,NOME VARCHAR(100) NOT NULL
    ,TIPO_LOCAL VARCHAR(50) NOT NULL
    ,CONSTRAINT PK_ID_LOCAL PRIMARY KEY (ID_LOCAL)
    ,CONSTRAINT UQ_NOME_LOCAL UNIQUE (NOME)
);
GO


CREATE TABLE TREINADOR (
     ID_TREINADOR INT NOT NULL
    ,NOME VARCHAR(100) NOT NULL
    ,TIPO_TREINADOR VARCHAR(50) NOT NULL
    ,CONSTRAINT PK_TREINADOR PRIMARY KEY (ID_TREINADOR)
    ,CONSTRAINT CK_TREINADOR_TIPO CHECK (TIPO_TREINADOR IN ('Protagonista', 'Rival', 'Lider de Ginasio', 'Treinador', 'Professor'))
);
GO


CREATE TABLE POKEMON_TIPO (
     ID_POKEMON INT NOT NULL
    ,ID_TIPO INT NOT NULL
    ,CONSTRAINT PK_POKEMON_TIPO PRIMARY KEY (ID_POKEMON, ID_TIPO)
    ,CONSTRAINT FK_POKEMON_TIPO_POKEMON FOREIGN KEY (ID_POKEMON) REFERENCES POKEMON (ID_POKEMON)
    ,CONSTRAINT FK_POKEMON_TIPO_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPO (ID_TIPO)
);
GO


CREATE TABLE POKEMON_LOCAL (
     ID_LOCAL INT NOT NULL
    ,ID_POKEMON INT NOT NULL
    ,CONSTRAINT PK_POKEMON_LOCAL PRIMARY KEY (ID_LOCAL, ID_POKEMON)
    ,CONSTRAINT FK_POKEMON_LOCAL_POKEMON FOREIGN KEY (ID_POKEMON) REFERENCES POKEMON (ID_POKEMON)
    ,CONSTRAINT FK_POKEMON_LOCAL_LOCAL FOREIGN KEY (ID_LOCAL) REFERENCES LOCAL (ID_LOCAL)
);
GO


CREATE TABLE EQUIPE_TREINADOR (
     ID_TREINADOR INT NOT NULL
    ,ID_POKEMON INT NOT NULL
    ,NIVEL TINYINT NOT NULL
    ,CONSTRAINT PK_EQUIPE_TREINADOR PRIMARY KEY (ID_TREINADOR, ID_POKEMON)
    ,CONSTRAINT FK_EQUIPE_TREINADOR_POKEMON FOREIGN KEY (ID_POKEMON) REFERENCES POKEMON (ID_POKEMON)
    ,CONSTRAINT FK_EQUIPE_TREINADOR_TREINADOR FOREIGN KEY (ID_TREINADOR) REFERENCES TREINADOR (ID_TREINADOR)
    ,CONSTRAINT CK_NIVEL CHECK (NIVEL >= 1 AND NIVEL <= 100)
);
GO


CREATE TABLE GINASIO (
     ID_GINASIO INT NOT NULL
    ,NOME VARCHAR(100) NOT NULL
    ,ID_LOCAL INT NOT NULL
    ,ID_LIDER INT NOT NULL
    ,ID_TIPO INT NOT NULL
    ,INSIGNIA VARCHAR(30) NOT NULL
    ,CONSTRAINT PK_ID_GINASIO PRIMARY KEY (ID_GINASIO)
    ,CONSTRAINT FK_ID_LOCAL_LOCAL FOREIGN KEY (ID_LOCAL) REFERENCES LOCAL (ID_LOCAL)
    ,CONSTRAINT FK_LIDER_TREINADOR FOREIGN KEY (ID_LIDER) REFERENCES TREINADOR (ID_TREINADOR)
    ,CONSTRAINT FK_TIPO_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPO (ID_TIPO)
);
GO
